### ISSUE TITLE
ringFile is not playing for the subsequent calls, after the first call is disconnected.

### ISSUE THREAD

**Issue by gh-harigajjala** [EvoluxBR/verto-docs#21]
Hi @StefanYohansson ,

I had implemented the Verto Communicator by following the steps from the below website,
http://evoluxbr.github.io/verto-docs/tut/getting-started.html

Every thing is working perfectly, except I am not able to hear the ringtone on the browser for the second call. The Scenario is,
1. Make a call from a 3rd party VOIP app (I am using Linphone) to the browser.
2. You will hear the Ringtone on the browser playing.
3. Accept the call and Disconnect the call.
4. Now make another call from app to browser.
5. You will not hear the Ringtone on the bowser.

I am seeing this issue only on Chrome and it works perfectly on Firefox.

Can you please guide me in solving this issue, as we want to implement the Verto Communicator in our Application.

Thanks for your help.

**Comment by victor-torres** [comment]
Any console log, @harigajjala?

**Comment by gh-harigajjala** [comment]
Hi @victor-torres 

This is the log for 2 subsequent calls, which I had described in the ticket.
[Verto_Call_Log.txt](https://github.com/EvoluxBR/verto-docs/files/963010/Verto_Call_Log.txt)

And this is my script file:
[main.txt](https://github.com/EvoluxBR/verto-docs/files/963049/main.txt)

**Comment by StefanYohansson** [comment]
Hi @harigajjala 

It seems like on second call it can't execute `.play()` method.

first call
```
jquery.FSRTC.js:267 REMOTE STREAM MediaStream {id: "q6l59NwvC9WlYMCJ5QHEd0cCxDDnoehF", active: true, onaddtrack: null, onremovetrack: null, onended: function…} <video id=​"video-container" autoplay=​"autoplay" class=​"video-style" src=​"sounds/​bell_ring2.wav" style=​"display:​ none;​">​</video>​
jquery.FSRTC.js:235 ICE Complete
```

second call
```
jquery.FSRTC.js:267 REMOTE STREAM MediaStream {id: "PRmyam9bd6Mp6HcMzldV0rq04kBnD3ij", active: true, onaddtrack: null, onremovetrack: null, onended: function…} <video id=​"video-container" autoplay=​"autoplay" class=​"video-style" src=​"sounds/​bell_ring2.wav" style=​"display:​ none;​">​</video>​
>>> jquery.min.js:3 Uncaught (in promise) DOMException: The play() request was interrupted by a new load request.
```

@harigajjala can you provide me whats your OS, chrome version and firefox version?

It could be related to this bug, since only chrome (chromium/webkit) is affected:
https://bugs.chromium.org/p/chromium/issues/detail?id=593273

can you apply this diff to verto project and try again?

```
diff --git a/html5/verto/js/src/jquery.FSRTC.js b/html5/verto/js/src/jquery.FSRTC.js
index a75dacca8f..38ac68faf3 100644
--- a/html5/verto/js/src/jquery.FSRTC.js
+++ b/html5/verto/js/src/jquery.FSRTC.js
@@ -241,6 +241,7 @@
                console.error('Error attaching stream to element.');
            }
        }
+        element.load();
     }
 
     

```

Thanks 🦊

**Comment by victor-torres** [comment]
I think I know what's happening here... The tutorial was made thinking about only one simultaneous call. In order to archive multiple simultaneous calls, you will need to use a **tag factory** instead of a specific audio/video tag.

```javascript
var createAudioTag = function() {
  var tagId = jQuery.verto.genUUID();
  var dialogAudioTag = $('<audio class="dialog-audio-tag"></audio>');
  dialogAudioTag.attr('id', tagId);
  $('body').append(dialogAudioTag);
  console.log("Generated new audio tag", dialogAudioTag);
  return dialogAudioTag;
}

var tagFactory = function() {
  var tag = createAudioTag();
  return tag.attr('id');
}
```

Instead of a string in the tag param of the bootstrap callback, you pass the reference to this tag factory callable. I'm almost sure the verto itself takes care of destroying this tag after the call end.

```diff
function bootstrap(status) {
  vertoHandle = new jQuery.verto({
    // ID of HTML video tag where the video feed is placed.
-    tag: "video-container",
+    tag: tagFactory,
    deviceParams: {
      // Asking for camera permissions and devices.
      useCamera: 'any',
      useMic: 'any',
      useSpeak: 'any',
    },
    // Other params...
  }, vertoCallbacks);
};
```

Could you check if this works? We should update the docs adding this information ASAP.

**Comment by gh-harigajjala** [comment]
Hi @victor-torres ,

The above fix worked for the Ringtone issue. Now I am able to hear the Ringtone for all the incoming calls. Thank you for the fix. And yes, after the call is ended this tag is getting destroyed.

But I am not able to view the video after this fix. 
I am unable to attach the browser console log here, but this is the Remote MediaStream I am getting now.

`jquery.FSRTC.js:267 REMOTE STREAM MediaStream <audio class=​"dialog-audio-tag" id=​"f55ebc53-958b-2780-32b2-ac1a1885dd83" style=​"display:​ block;​">​</audio>​
`
After these changes I am not seeing the DOMException anymore.

**Comment by gh-harigajjala** [comment]
Hi @StefanYohansson,

After applying the changes you specified to jquery.FSRTC.js file, I am not getting any DOMException, but it didn't fixed the actual problem.

My environment is:
OS : macOS Sierra v10.12.4
chrome version : 57.0.2987.133 (64-bit)
firefox version : 53.0 (64-bit)

**Comment by victor-torres** [comment]
@harigajjala just to make sure, are you using a video tag instead of an audio one? 

```diff
- var createAudioTag = function() {
+ var createVideoTag = function() {
  var tagId = jQuery.verto.genUUID();
-  var dialogAudioTag = $('<audio class="dialog-audio-tag"></audio>');
+  var dialogVideoTag = $('<video class="dialog-audio-tag"></video>');
-  dialogAudioTag.attr('id', tagId);
+  dialogVideoTag.attr('id', tagId);
-  $('body').append(dialogAudioTag);
+  $('body').append(dialogVideoTag);
-  console.log("Generated new audio tag", dialogAudioTag);
+  console.log("Generated new video tag", dialogVideoTag);
-  return dialogAudioTag;
+  return dialogVideoTag;
}

var tagFactory = function() {
-  var tag = createAudioTag();
+  var tag = createVideoTag();
  return tag.attr('id');
}
```

**Comment by StefanYohansson** [comment]
@harigajjala 

> But I am not able to view the video after this fix.

If you're using a `<audio>` tag in createAudioTag function, you only receive audio.
try to use a `<video>` tag if you want video+audio.

**Comment by gh-harigajjala** [comment]
@victor-torres, @StefanYohansson 
Yes I had used the Video tag in the createAudioTag function to receive Video, but the problem was I had a pre-defined Video element in HTML and want to display the Video in that element.

If I take out the Video element in HTML, I am able to display the Video but I want the Video in the HTML element.

**Comment by victor-torres** [comment]
I think you'll need to reposition your video tag right after creating it. Is it possible? Try to add some class or trigger a JavaScript method for it.

**Comment by royalpinto** [comment]
@victor-torres Is the `tag` attribute documented somewhere ?
I had a similar situation in which when one call is active, we had to make one more call to check with another agent if first call can be transferred to second agent. In this scenario, if second call is cancelled, and first call is resumed back, audio was silent. This was because when making a second call, for the audio tag new call's stream was getting assigned. When second call is cancelled, the stream was still of the second call. After spending lot of time on this issue I figured out what exactly was happening.
By using `tagFactory`, issue got resolved as it creates a new audio tag for every new call.

Thanks 👍

**Comment by victor-torres** [comment]
I'm glad it helped you, @royalpinto. I'm afraid this isn't documented anywhere. Would you like to submit a pull request updating our doc files? :)

**Comment by royalpinto** [comment]
Thanks @victor-torres here is the PR: https://github.com/EvoluxBR/verto-docs/pull/22

**Comment by victor-torres** [comment]
Thank you.
