### ISSUE TITLE
DTMF not work on Outgoing calls

### ISSUE THREAD

**Issue by matiasr2503** [EvoluxBR/verto-docs#39]
Hi guys! I have problems when I send a dtmf on outgoing calls, the tone is not sent, but it is logged by the console that sends the event. On incoming calls it works correctly. If someone happens the same thing or knows a solution I would appreciate it

**Comment by victor-torres** [comment]
Hey, @matiasr2503. 

I'm sorry that you're having such a problem. 

Since you've said that the DTMF is being logged, I suspect the problem might not be with verto. 

Are you using any SIP provider or are you connected directly with the PSTN? Sometimes those providers have some problems forwarding DTMF tones. Or you possibly have a codec misconfiguration or so.

The fact is that it's quite difficult to help without having access to complete call logs (omitting private information).

**Comment by victor-torres** [comment]
@italorossi, I think we could close this issue since:
- it doesn't seem to be a problem with the verto JavaScript lib
- we haven't got any answer for more than a week

**Comment by italorossi** [comment]
Sure, thanks @victor-torres !
